name: lily
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  #ui
  easy_localization: ^3.0.2
  flutter_screenutil: ^5.8.0
  cached_network_image: ^3.2.2
  confetti: ^0.7.0
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  date_format: ^2.0.6
  dio: ^5.3.3
  equatable: ^2.0.5
  flare_flutter: ^3.0.2
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^9.0.0
  flutter_svg:
  get_it: ^7.2.0
  intl: ^0.18.0
  json_annotation: ^4.7.0
  pull_to_refresh: ^2.0.0
  retrofit: ^4.0.3
  rubber: ^1.0.1
  rive: ^0.11.17
  uuid: ^4.1.0
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.5
  go_router: ^12.0.0
  pin_code_fields: ^8.0.1
  flutter_switch: ^0.3.2
  in_app_purchase: ^3.0.8
  share_plus: ^7.2.1
  url_launcher: ^6.1.6
  in_app_review: ^2.0.4
  notification_permissions: ^0.6.1
  badges: ^3.1.2
  soundpool: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
  # images 
   - assets/images/logo/app_logo.png
   - assets/images/logo/lily_logo.png
   - assets/images/completed.png
   - assets/images/loading.png
   - assets/images/product-background.png

  # bouquets
   - assets/images/bouquets/image1.png
   - assets/images/bouquets/image2.png
   - assets/images/bouquets/image3.png
   - assets/images/bouquets/image4.png
   - assets/images/bouquets/image5.png
   - assets/images/bouquets/image6.png
   - assets/images/bouquets/image7.png
   - assets/images/bouquets/image8.png

   # indoor
   - assets/images/indoor/image1.png
   - assets/images/indoor/image2.png
   - assets/images/indoor/image3.png
   - assets/images/indoor/image4.png
   - assets/images/indoor/image5.png
   - assets/images/indoor/image6.png
   - assets/images/indoor/image7.png
   - assets/images/indoor/image8.png

  # outdoor
   - assets/images/outdoor/image1.png
   - assets/images/outdoor/image2.png
   - assets/images/outdoor/image3.png
   - assets/images/outdoor/image4.png
   - assets/images/outdoor/image5.png
   - assets/images/outdoor/image6.png
   - assets/images/outdoor/image7.png
   - assets/images/outdoor/image8.png

   # workshops
   - assets/images/workshops/image1.png
   - assets/images/workshops/image2.png
   - assets/images/workshops/image3.png
   - assets/images/workshops/image4.png
   - assets/images/workshops/image5.png
   - assets/images/workshops/image6.png
